[pytest]
markers =
    need_review: tests that are checked during the course review
    login_guest: guest navigation to the login page
    add_to_basket: guest scenarios on the product page
    user_add_to_basket: registered user scenarios on the product page
